name: Build Library Artifacts

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true

    - name: Build library
      run: bundle exec rake compile

    - name: Set OS name
      id: os-name
      run: |
        if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
          echo "name=linux" >> $GITHUB_OUTPUT
        else
          echo "name=darwin" >> $GITHUB_OUTPUT
        fi

    - name: Package files
      run: |
        mkdir dist
        cp -r include dist/
        cp build/libprism.a dist/
        tar -czf prism-${{ steps.os-name.outputs.name }}.tar.gz -C dist .

    - name: Upload to release
      if: github.event_name == 'release'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: softprops/action-gh-release@v2
      with:
        files: prism-${{ steps.os-name.outputs.name }}.tar.gz
